---
- name: Configure machine
  hosts: local
  gather_facts: yes

  tasks:
    - name: Check for vars file by distribution
      stat:
        path: "{{ ansible_distribution | lower}}.yml"
      register: has_os_vars

    - name: Include OS vars
      include_vars:
        file: "{{ ansible_distribution | lower}}.yml"
      when: has_os_vars.stat.exists

    - name: Check for vars file by hostname
      stat:
        path: "{{ ansible_hostname }}.yml"
      register: has_vars

    - name: Include vars
      include_vars:
        file: "{{ ansible_hostname }}.yml"
      when: has_vars.stat.exists

    - name: Set roles
      include_role:
        name: "{{ ansible_distribution | lower }}"
