---
- name: Check if displayplacer is installed
  command: which displayplacer
  register: displayplacer_check
  changed_when: false
  ignore_errors: yes

- name: set resolution
  command: >
    displayplacer 'id:{{ displayplacer_item.context_id }}
    res:{{ displayplacer_item.resolution }}
    hz:{{ displayplacer_item.refresh_rate }}
    color_depth:{{ displayplacer_item.color_depth }}
    scaling:{{ displayplacer_item.scaling }}
    origin:{{ displayplacer_item.origin }}
    degree:{{ displayplacer_item.rotation }}'
  when: displayplacer_check.rc == 0
  loop: "{{ displays }}"
  loop_control:
    loop_var: displayplacer_item